version: '3'
services:
  db: 
    image: postgres
    networks: 
      - webnet
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: picby_db
    volumes:
      -  ${WEBAPP_STORAGE_HOME}/pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
  web:
    image: picby_graphql_api
    ports: 
      - "8081:8081"
    networks:
      - webnet
    environment: 
      REDIS_URL: redis://redis:6379/0
      DB_HOST: db
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "index.js"]
  redis:
    image: redis
    ports:
    - "6379:6379" 
    networks:
      - webnet
networks: 
  webnet: